project:
  title: "exercises"
  type: website
  output-dir: ../docs
  
format:
  html:
    html-math-method: katex
    code-fold: true
    toc: true
    toc-location: left
    css: styles/activities.css
    include-before-body: header.html
